import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import RQProvider from "./_components/RQProvider";
import Header from "./_components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RQProvider>
          <Header />
          <main>{children}</main>
        </RQProvider>
      </body>
    </html>
  );
}
